// generate-patterns.js
// Writes a helper that automatically imports every JSON file in src/patterns via webpack's require.context.
const fs = require('fs').promises;
const path = require('path');

const GENERATED_CONTENT = `// This file is auto-generated by generate_patterns.js
// Patterns are loaded dynamically from src/patterns via webpack's require.context.

const patternsContext = require.context('./patterns', true, /\\.json$/);

const patternLibrary = patternsContext.keys().reduce((library, key) => {
    const module = patternsContext(key);
    const pattern = module.default || module;

    const cleanPath = key.replace(/^\\.\\//, '');
    const segments = cleanPath.split('/');
    const fileName = segments.pop();
    const modeKey = segments[0] || 'classic';
    const patternName = pattern.name || fileName.replace(/\\.json$/, '');

    if (!library[modeKey]) {
        library[modeKey] = {};
    }
    library[modeKey][patternName] = pattern;
    return library;
}, {});

const defaultMode = patternLibrary.classic ? 'classic' : Object.keys(patternLibrary)[0] || 'classic';

export const getPatternsForMode = (modeKey = defaultMode) => patternLibrary[modeKey] || patternLibrary[defaultMode] || {};

export default patternLibrary;
`;

async function generatePatternsModule() {
    try {
        const targetPath = path.join(__dirname, 'src/generated-patterns.js');
        await fs.writeFile(targetPath, GENERATED_CONTENT, 'utf8');
        console.log('Generated patterns module using require.context loader.');
    } catch (error) {
        console.error('Error generating patterns module:', error);
        process.exit(1);
    }
}

generatePatternsModule();
